[tool.poetry]
name = "lws_backend"
version = "0.1.0"
description = ""
authors = ["Alex Korzh <alexkorzh7@gmail.com>"]
license = "The Unlicense"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
